### ISSUE TITLE
Code doesn't compile with boost 1.67

### ISSUE THREAD

**Issue by Fierthraix** [bastibl/gr-foo#10]
The release of boost 1.67 [fixes](https://github.com/boostorg/date_time/pull/64) an [issue](https://svn.boost.org/trac10/ticket/11168) where floating point values are automatically converted into integers for the constructors of `boost::posix_time::time_duration`, and helper functions like `boost::posix_time::milliseconds(float)`. This causes errors when special values (NaN, -∞, etc) are passed to it.

Currently the `d_duration` value in Periodic Message Source and Random Periodic Message source pass a float to `boost::posix_time::milliseconds` [here](https://github.com/bastibl/gr-foo/blob/cb74ba2be81096213c4b981d43131e42e77ed815/lib/periodic_msg_source_impl.cc#L86) and [here](https://github.com/bastibl/gr-foo/blob/cb74ba2be81096213c4b981d43131e42e77ed815/lib/random_periodic_msg_source_impl.cc#L92).

This creates [a pretty large compiler error](https://gist.github.com/Fierthraix/0034f053654d27f1ef845b39a04ded12).

**Comment by bastibl** [comment]
I merged the PR. Thank you.
