### ISSUE TITLE
cant install it errors

### ISSUE THREAD

**Issue by girs1982** [bastibl/gr-foo#14]
CMake Error at CMakeLists.txt:98 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.8".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake, version: 3.7.9.1

-- Configuring incomplete, errors occurred!
See also "/home/ubludok/gr-foo/build/CMakeFiles/CMakeOutput.log".

**Comment by bastibl** [comment]
This was already addressed here: https://github.com/bastibl/gr-foo/issues/13. The solution is to use the correct branch. Please see the readme.

**Comment by girs1982** [comment]
how it do??? i read it many times

**Comment by bastibl** [comment]
You checkout the correct branch in git. Please see many of the great tutorials on how to use git.

**Comment by girs1982** [comment]
where it is,i dont know how

**Comment by bastibl** [comment]
Use the search engine of your choice to search for a git tutorial.
