### ISSUE TITLE
Compilation Error!!

### ISSUE THREAD

**Issue by r00tb3** [bastibl/gr-foo#15]
I'm stuck at the following error:-

```
$ git branch 
* maint-3.7
  maint-3.8

```

```
$ cmake ../
-- Build type not specified: defaulting to release.
-- UHD library found.
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: ANALOG
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-analog.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so;/usr/lib/x86_64-linux-gnu/libvolk.so
GNURADIO_ANALOG_FOUND = TRUE
Checking for GNU Radio Module: BLOCKS
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-blocks.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_BLOCKS_FOUND = TRUE
Checking for GNU Radio Module: DIGITAL
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-digital.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_DIGITAL_FOUND = TRUE
Checking for GNU Radio Module: FFT
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-fft.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_FFT_FOUND = TRUE
Checking for GNU Radio Module: FILTER
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-filter.so;/usr/lib/x86_64-linux-gnu/libgnuradio-fft.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_FILTER_FOUND = TRUE
Checking for GNU Radio Module: PMT
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_PMT_FOUND = TRUE
-- Extracting version information from git describe...
CMake Error at /usr/local/lib/cmake/gnuradio/GrMiscUtils.cmake:177 (install):
  install FILES given no DESTINATION!
Call Stack (most recent call first):
  lib/CMakeLists.txt:74 (GR_LIBRARY_FOO)


-- Using install prefix: /usr/local
-- Building for version: d26261fa / 3.8git
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.8.
-- Found PythonLibs: /usr/local/lib/libpython3.6m.a (found version "3.6.9") 
-- Found PythonLibs: /usr/local/lib/libpython3.6m.a (found suitable version "3.6.9", minimum required is "2") 
-- Configuring incomplete, errors occurred!

```

What am I  missing here?

I've tried compiling for 3.8 branches too I receive the same error.

Regards.

**Comment by bastibl** [comment]
What does `gnuradio-config -v` output?
What distro are you using? I assume you used the package manager to install GNU Radio.
If there is a `-dev` package for GNU Radio, please install it as well.

**Comment by r00tb3** [comment]
> gnuradio-config -v

gnuradio-config-info -v
3.7.13.5

gnuradio-companion --v
GNU Radio Companion 3.7.10

It shows two different versions installed. 

Also, I've installed GNURadio using pybombs as manual installation through source gives a compilation error.  

> What distro are you using? 
Lubuntu 16.04.04 LTS

> If there is a -dev package for GNU Radio, please install it as well.
It's already installed.

**Comment by bastibl** [comment]
From the other issues that you opened, I understand that you installed GNU Radio with PyBombs. This issue suggests that you also installed the version from your package manager. I assume PyBombs compiled GNU Radio from source, so you ended up with two installations. Please remove the one from the package manager, source the pybombs environment and try again.

**Comment by r00tb3** [comment]
> source the pybombs environment 

What does this mean?

> remove the one from the package manager

OK.

**Comment by bastibl** [comment]
> What does this mean?

https://github.com/gnuradio/pybombs#quickstart

**Comment by r00tb3** [comment]
> > What does this mean?
> 
> https://github.com/gnuradio/pybombs#quickstart

Sorry I had done this already did see it properly.

**Comment by r00tb3** [comment]
> > source the pybombs environment
> 
> What does this mean?
> 
> > remove the one from the package manager
> 
> OK.

@bastibl Okay!! I did this now I'm running gnuradio version 3.7.13.5

Just launched the gnuradio-companion still I'm not able to load the grc files of ieee802_15_4_CSS_PHY.grc and transceiver_OQPSK.grc

**Comment by bastibl** [comment]
Please continue the discussion about your issues with grc flow graphs in the corresponding issue:
https://github.com/bastibl/gr-ieee802-15-4/issues/44
