### ISSUE TITLE
generating a DOI

### ISSUE THREAD

**Issue by rs-development** [bastibl/gr-foo#16]
Since your doing great work which is worth citing, i think you should consider creating a DIO for your work.

https://guides.github.com/activities/citable-code/

**Comment by bastibl** [comment]
Hmm... To be honest, I didn't think about that. But what might be better than a citation of the software, would be a citation of the papers that introduce the tool. For my 802.11 transceiver and my 802.15.4, I have two papers listed on the publications website:
https://www.wime-project.net/publications/
Do you use gr-foo independent from these transceivers?

**Comment by rs-development** [comment]
I did not notice you have papers for your software. Awesome!

I just grabbed the example from the https://github.com/bastibl/gr-ieee802-15-4 repo.
