### ISSUE TITLE
Gnuradio has settled on new version number, so gr-foo master no longer builds against it

### ISSUE THREAD

**Issue by flaviusb** [bastibl/gr-foo#17]
Gnuradio updated their version number in master to 3.9 in commit https://github.com/gnuradio/gnuradio/commit/f1475ce5eea60d4780621b5f62b8c7a226cd29a9 .

gr-foo master currently checks for gnuradio version 3.8 in https://github.com/bastibl/gr-foo/blob/maint-3.8/CMakeLists.txt#L98, so it does not build against the most recent gnuradio master.

**Comment by bastibl** [comment]
thanks!
