### ISSUE TITLE
Some error occur when executing cmake 

### ISSUE THREAD

**Issue by yufu186** [bastibl/gr-foo#25]
Hi, after following the tutorial in "https://wiki.gnuradio.org/index.php/InstallingGR#To_install_system_wide", I install the Gnuradio 3.7.2.1 on Ubuntu 14.04. When I executed common "cmake" in the build file in gr-foo, some error occur:
yufu@ubuntu:~/802/gr-foo/build1$ cmake ..
-- Build type not specified: defaulting to release.
-- checking for module 'uhd'
--   package 'uhd' not found
-- Could NOT find UHD (missing:  UHD_LIBRARIES UHD_INCLUDE_DIRS) 
-- UHD library not found, no support for timed TX.
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   thread
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: ANALOG
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-analog.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_ANALOG_FOUND = TRUE
Checking for GNU Radio Module: BLOCKS
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-blocks.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_BLOCKS_FOUND = TRUE
Checking for GNU Radio Module: FILTER
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-filter.so;/usr/lib/x86_64-linux-gnu/libgnuradio-fft.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_FILTER_FOUND = TRUE
Checking for GNU Radio Module: PMT
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_PMT_FOUND = TRUE
CMake Error at lib/CMakeLists.txt:46 (include):
  include could not find load file:

    GnuradioConfigVersion

CMake Error at lib/CMakeLists.txt:48 (if):
  if given arguments:

    "EQUAL" "8"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/yufu/802/gr-foo/build1/CMakeFiles/CMakeOutput.log".
CMake Error: Unable to open check cache file for write. /home/yufu/802/gr-foo/build1/CMakeFiles/cmake.check_cache

1. I think this error means that GnuradioConfigVersion is not found. so I execute "find" command, 
In path "/usr/lib/x86_64-linux-gnu/cmake/gnuradio" I find "GnuradioConfigVersion.cmake" 
Is this file that the "cmake" command need ? 
If so, why the file can't be found when executing cmake ?
If not, how I can solve this problem ?

I am looking forward to your reply as soon as possible !

**Comment by bastibl** [comment]
You are using a 6 year old distribution with a 7 year old version of GNU Radio. Please update your system.

**Comment by yufu186** [comment]
> You are using a 6 year old distribution with a 7 year old version of GNU Radio. Please update your system.

Thanks for reply! I will close this issue.
