### ISSUE TITLE
CMake Issues 

### ISSUE THREAD

**Issue by armandsarkani** [bastibl/gr-foo#26]
Hello,

I am trying to install gr-foo and while running CMake using `cmake ..` on the maint-3.8 branch I run into the following error:
```
CMake Error at swig/CMakeLists.txt:36 (include):
  include could not find load file:

    GrSwig


CMake Error at swig/CMakeLists.txt:50 (GR_SWIG_MAKE):
  Unknown CMake command "GR_SWIG_MAKE".
```
A screenshot of the entire output of CMake is shown below:

<img width="682" alt="Screen Shot 2020-12-29 at 5 21 34 PM" src="https://user-images.githubusercontent.com/52443124/103324003-50222a00-49fa-11eb-9a78-1e85f970215c.png">

I have tried installing Swig on my machine and re-doing the build process, but it doesn't seem to work. Also, I cannot find the `GrSwig` module inside `cmake/Modules` for the 3.8 branch, but it does exist in the 3.7 branch. I have tried using all three branches, and even copied the GrSwig file from the 3.7 branch to my local 3.8 copy and that didn't work either. I also tried commenting out the error lines in `swig/CMakeLists.txt` and running CMake, which worked successfully, however, when I ran `make`, I immediately got an error.

I am trying to build gr-foo and gr-ieee80211 on a Raspberry Pi running Raspbian.

Any ideas how I can make this work?

**Comment by bastibl** [comment]
Maybe you only have `gnuradio` but not `gnuradio-dev` installed?

**Comment by armandsarkani** [comment]
I built GNU Radio from source, but I'll look into that.

**Comment by bastibl** [comment]
I see. In that case, there should be a `GrSwig.cmake` file at `<install prefix>/lib/cmake/gnuradio`.
Make sure that this file exists.  If so, the question is why cmake doesn't find it. Did you install GNU Radio under `/usr/local`?

**Comment by armandsarkani** [comment]
Thanks, yes I did install GNU Radio 3.8 under `/usr/local`.

**Comment by bastibl** [comment]
You probably installed GNU Radio without Python support (or at least without Python-bindings, since Swig was probably not installed when you compiled GNU Radio).

**Comment by armandsarkani** [comment]
Okay thanks for your help, I will look into that.
