### ISSUE TITLE
Cmake issue

### ISSUE THREAD

**Issue by Alexis000000** [bastibl/gr-foo#29]
Hello,

I am trying to install the gr-foo but I encountered the following error.
-- UHD library found.
CMake Error at CMakeLists.txt:88 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.9".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.3.git

-- Configuring incomplete, errors occurred!
See also "/xxx/xxx/workarea/gr-foo/build/CMakeFiles/CMakeOutput.log".

I have installed the GNU Radio 3.8 but I do not understand why the make file keeps looking for the 3.9 one.
Can anyone help me ?

Thank you
Ali

**Comment by bastibl** [comment]
Hi.
Citing from the readme:

> Like GNU Radio, this module uses maint branches for development. These branches are supposed to be used with the corresponding GNU Radio branches. This means: the maint-3.7 branch is compatible with GNU Radio 3.7, maint-3.8 is compatible with GNU Radio 3.8, etc.

That means you'll have to use the maint-3.8 branch of this module to use it with GNU Radio 3.8.
