### ISSUE TITLE
 ./build_oai -w USRP --ninja --gNB -C    Could not find a package configuration file provided by "UHD" with any of   the following names:      UHDConfig.cmake     uhd-config.cmake

### ISSUE THREAD

**Issue by sebastian2341** [bastibl/gr-foo#36]
Hello. I am currently attempting to build the OAI with the USRP option by running the command:

git clone https://gitlab.eurecom.fr/oai/openairinterface5g.git ~/openairinterface5g
cd ~/openairinterface5g
git checkout develop

# Install OAI dependencies
cd ~/openairinterface5g/cmake_targets
./build_oai -I

# Build OAI gNB
cd ~/openairinterface5g
source oaienv
cd cmake_targets
./build_oai -w USRP --ninja --gNB -C

I am encountering several errors during the build process. Below is the detailed output:
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Ccache not found. Consider installing it for faster compilation. Command: sudo apt/dnf install ccache
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Check if /opt/asn1c/bin/asn1c supports -gen-APER
-- Check if /opt/asn1c/bin/asn1c supports -no-gen-UPER
-- Check if /opt/asn1c/bin/asn1c supports -no-gen-JER
-- Check if /opt/asn1c/bin/asn1c supports -no-gen-BER
-- Check if /opt/asn1c/bin/asn1c supports -no-gen-OER
-- CMAKE_BUILD_TYPE is RelWithDebInfo
-- CPU architecture is x86_64
-- AVX512 intrinsics are OFF
-- AVX2 intrinsics are ON
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Selected E2AP_VERSION: E2AP_V2
-- Selected KPM Version: KPM_V2_03
-- Checking for module 'libconfig'
--   Found libconfig, version 1.5
-- Checking for module 'openssl'
--   Found openssl, version 3.0.2
-- Checking for module 'blas'
--   Found blas, version 3.10.3
-- Checking for module 'lapacke'
--   Found lapacke, version 3.10.0
-- Checking for module 'cblas'
--   No package 'cblas' found
-- No Support for Aerial
-- No Doxygen documentation requested
CMake Error at radio/USRP/CMakeLists.txt:2 (find_package):
  By not providing "FindUHD.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "UHD", but
  CMake did not find one.

  Could not find a package configuration file provided by "UHD" with any of
  the following names:

    UHDConfig.cmake
    uhd-config.cmake

  Add the installation prefix of "UHD" to CMAKE_PREFIX_PATH or set "UHD_DIR"
  to a directory containing one of the above files.  If "UHD" provides a
  separate development package or SDK, be sure it has been installed.

How to solve this? I read that is a branch issue but I don't know how to solve it.

**Comment by bastibl** [comment]
This repository has nothing to do with OAI.
