### ISSUE TITLE
Compile errror

### ISSUE THREAD

**Issue by rd15armas** [bastibl/gr-foo#6]
Hello I have get these error: but gnuradio have not "mmse_resampler_cc.h" in https://github.com/gnuradio/gnuradio/tree/master/gr-filter/include/gnuradio/filter

Could you help me please..

[  4%] Building CXX object lib/CMakeFiles/gnuradio-foo.dir/channel_model_impl.cc.o
In file included from /home/hp/sdr/gr-foo/lib/channel_model_impl.cc:18:0:
/home/hp/sdr/gr-foo/lib/channel_model_impl.h:27:47: fatal error: gnuradio/filter/mmse_resampler_cc.h: No such file or directory
 #include <gnuradio/filter/mmse_resampler_cc.h>
                                               ^
compilation terminated.

**Comment by bastibl** [comment]
Citing the second sentence of the readme:

> Like GNU Radio, this module uses *master* and *next* branches for development, which are supposed to be used with the corresponding GNU Radio branches.

Make sure that this is the case for you.
